name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v5
        with:
          path: "src"

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v5
        with:
          ref: "builds"
          path: "builds"

      - name: Eski Derlemeleri Temizle
        run: |
          rm -f "$GITHUB_WORKSPACE"/builds/*.cs3
          rm -f "$GITHUB_WORKSPACE"/builds/plugins.json

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v4

      - name: Android SDK Paketlerini Hazırla
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Android SDK Lisanslarını Kabul Et
        run: |
          yes | sdkmanager --licenses > /dev/null || true

      - name: Android SDK Paketlerini Tekrar Kontrol Et
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Eklentileri Derle
        run: |
          cd "$GITHUB_WORKSPACE/src"

          chmod +x gradlew

          ./gradlew make makePluginsJson

          find . -type f -name "*.cs3" -exec cp {} "$GITHUB_WORKSPACE/builds/" \;

          if [ -f "build/plugins.json" ]; then
            cp "build/plugins.json" "$GITHUB_WORKSPACE/builds/"
          fi

      - name: Derlemeleri Yükle
        run: |
          cd "$GITHUB_WORKSPACE/builds"

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add .

          if git diff --cached --quiet; then
            echo "Yeni bir değişiklik yok."
            exit 0
          fi

          git commit -m "CloudStream eklentileri derlendi: $GITHUB_SHA"

          git push origin builds
