```yaml
name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # Ana kaynak kodlarını indir
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v5
        with:
          path: "src"

      # Derlenmiş dosyaların bulunduğu builds branch'ini indir
      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v5
        with:
          ref: "builds"
          path: "builds"

      # Eski .cs3 dosyalarını temizle
      - name: Eski Derlemeleri Temizle
        run: |
          rm -f "$GITHUB_WORKSPACE"/builds/*.cs3

      # Java 17
      - name: JDK 17 Ayarla
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Android SDK ortamını hazırla
      - name: Android SDK Ortamını Hazırla
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> "$GITHUB_ENV"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> "$GITHUB_ENV"

          yes | sdkmanager --licenses > /dev/null || true

          sdkmanager "platform-tools"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"

      # Eklentileri derle
      - name: Eklentileri Derle
        run: |
          cd "$GITHUB_WORKSPACE/src"

          chmod +x gradlew

          ./gradlew make makePluginsJson

          find . -type f -name "*.cs3" -exec cp {} "$GITHUB_WORKSPACE/builds/" \;

          if [ -f "build/plugins.json" ]; then
            cp "build/plugins.json" "$GITHUB_WORKSPACE/builds/"
          fi

      # Derlenmiş dosyaları builds branch'ine gönder
      - name: Derlemeleri Yükle
        run: |
          cd "$GITHUB_WORKSPACE/builds"

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add .

          if git diff --cached --quiet; then
            echo "Yeni bir değişiklik yok."
            exit 0
          fi

          git commit -m "CloudStream eklentileri derlendi: $GITHUB_SHA"

          git push origin builds
```
